# The Docker image to run your workspace in.
image:
  file: .gitpod.dockerfile

# Command to start on workspace startup   
tasks:
 - init: . ${GITPOD_REPO_ROOT}/init_tasks.sh    

# Ports to expose on workspace startup
ports:
  - port: 8000

vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
